/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MallsIndexRouteImport } from './routes/malls/index'
import { Route as OwnerRegisterMallRouteImport } from './routes/owner/register-mall'
import { Route as OwnerMallsRouteImport } from './routes/owner/malls'
import { Route as OwnerGuardsRouteImport } from './routes/owner/guards'
import { Route as MallsMallIdRouteImport } from './routes/malls/$mallId'
import { Route as GuardScanRouteImport } from './routes/guard/scan'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminPendingRouteImport } from './routes/admin/pending'
import { Route as AdminManageRouteImport } from './routes/admin/manage'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as OwnerFloorsMallIdRouteImport } from './routes/owner/floors.$mallId'
import { Route as OwnerDashboardMallIdRouteImport } from './routes/owner/dashboard.$mallId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MallsIndexRoute = MallsIndexRouteImport.update({
  id: '/malls/',
  path: '/malls/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRegisterMallRoute = OwnerRegisterMallRouteImport.update({
  id: '/register-mall',
  path: '/register-mall',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerMallsRoute = OwnerMallsRouteImport.update({
  id: '/malls',
  path: '/malls',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerGuardsRoute = OwnerGuardsRouteImport.update({
  id: '/guards',
  path: '/guards',
  getParentRoute: () => OwnerRoute,
} as any)
const MallsMallIdRoute = MallsMallIdRouteImport.update({
  id: '/malls/$mallId',
  path: '/malls/$mallId',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardScanRoute = GuardScanRouteImport.update({
  id: '/guard/scan',
  path: '/guard/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPendingRoute = AdminPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManageRoute = AdminManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const OwnerFloorsMallIdRoute = OwnerFloorsMallIdRouteImport.update({
  id: '/floors/$mallId',
  path: '/floors/$mallId',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerDashboardMallIdRoute = OwnerDashboardMallIdRouteImport.update({
  id: '/dashboard/$mallId',
  path: '/dashboard/$mallId',
  getParentRoute: () => OwnerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookings': typeof BookingsRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRouteWithChildren
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/manage': typeof AdminManageRoute
  '/admin/pending': typeof AdminPendingRoute
  '/admin/users': typeof AdminUsersRoute
  '/guard/scan': typeof GuardScanRoute
  '/malls/$mallId': typeof MallsMallIdRoute
  '/owner/guards': typeof OwnerGuardsRoute
  '/owner/malls': typeof OwnerMallsRoute
  '/owner/register-mall': typeof OwnerRegisterMallRoute
  '/malls/': typeof MallsIndexRoute
  '/owner/dashboard/$mallId': typeof OwnerDashboardMallIdRoute
  '/owner/floors/$mallId': typeof OwnerFloorsMallIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookings': typeof BookingsRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRouteWithChildren
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/manage': typeof AdminManageRoute
  '/admin/pending': typeof AdminPendingRoute
  '/admin/users': typeof AdminUsersRoute
  '/guard/scan': typeof GuardScanRoute
  '/malls/$mallId': typeof MallsMallIdRoute
  '/owner/guards': typeof OwnerGuardsRoute
  '/owner/malls': typeof OwnerMallsRoute
  '/owner/register-mall': typeof OwnerRegisterMallRoute
  '/malls': typeof MallsIndexRoute
  '/owner/dashboard/$mallId': typeof OwnerDashboardMallIdRoute
  '/owner/floors/$mallId': typeof OwnerFloorsMallIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookings': typeof BookingsRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRouteWithChildren
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/manage': typeof AdminManageRoute
  '/admin/pending': typeof AdminPendingRoute
  '/admin/users': typeof AdminUsersRoute
  '/guard/scan': typeof GuardScanRoute
  '/malls/$mallId': typeof MallsMallIdRoute
  '/owner/guards': typeof OwnerGuardsRoute
  '/owner/malls': typeof OwnerMallsRoute
  '/owner/register-mall': typeof OwnerRegisterMallRoute
  '/malls/': typeof MallsIndexRoute
  '/owner/dashboard/$mallId': typeof OwnerDashboardMallIdRoute
  '/owner/floors/$mallId': typeof OwnerFloorsMallIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bookings'
    | '/login'
    | '/owner'
    | '/register'
    | '/admin/dashboard'
    | '/admin/manage'
    | '/admin/pending'
    | '/admin/users'
    | '/guard/scan'
    | '/malls/$mallId'
    | '/owner/guards'
    | '/owner/malls'
    | '/owner/register-mall'
    | '/malls/'
    | '/owner/dashboard/$mallId'
    | '/owner/floors/$mallId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bookings'
    | '/login'
    | '/owner'
    | '/register'
    | '/admin/dashboard'
    | '/admin/manage'
    | '/admin/pending'
    | '/admin/users'
    | '/guard/scan'
    | '/malls/$mallId'
    | '/owner/guards'
    | '/owner/malls'
    | '/owner/register-mall'
    | '/malls'
    | '/owner/dashboard/$mallId'
    | '/owner/floors/$mallId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bookings'
    | '/login'
    | '/owner'
    | '/register'
    | '/admin/dashboard'
    | '/admin/manage'
    | '/admin/pending'
    | '/admin/users'
    | '/guard/scan'
    | '/malls/$mallId'
    | '/owner/guards'
    | '/owner/malls'
    | '/owner/register-mall'
    | '/malls/'
    | '/owner/dashboard/$mallId'
    | '/owner/floors/$mallId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookingsRoute: typeof BookingsRoute
  LoginRoute: typeof LoginRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  GuardScanRoute: typeof GuardScanRoute
  MallsMallIdRoute: typeof MallsMallIdRoute
  MallsIndexRoute: typeof MallsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/malls/': {
      id: '/malls/'
      path: '/malls'
      fullPath: '/malls/'
      preLoaderRoute: typeof MallsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/register-mall': {
      id: '/owner/register-mall'
      path: '/register-mall'
      fullPath: '/owner/register-mall'
      preLoaderRoute: typeof OwnerRegisterMallRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/malls': {
      id: '/owner/malls'
      path: '/malls'
      fullPath: '/owner/malls'
      preLoaderRoute: typeof OwnerMallsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/guards': {
      id: '/owner/guards'
      path: '/guards'
      fullPath: '/owner/guards'
      preLoaderRoute: typeof OwnerGuardsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/malls/$mallId': {
      id: '/malls/$mallId'
      path: '/malls/$mallId'
      fullPath: '/malls/$mallId'
      preLoaderRoute: typeof MallsMallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guard/scan': {
      id: '/guard/scan'
      path: '/guard/scan'
      fullPath: '/guard/scan'
      preLoaderRoute: typeof GuardScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pending': {
      id: '/admin/pending'
      path: '/pending'
      fullPath: '/admin/pending'
      preLoaderRoute: typeof AdminPendingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manage': {
      id: '/admin/manage'
      path: '/manage'
      fullPath: '/admin/manage'
      preLoaderRoute: typeof AdminManageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/owner/floors/$mallId': {
      id: '/owner/floors/$mallId'
      path: '/floors/$mallId'
      fullPath: '/owner/floors/$mallId'
      preLoaderRoute: typeof OwnerFloorsMallIdRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/dashboard/$mallId': {
      id: '/owner/dashboard/$mallId'
      path: '/dashboard/$mallId'
      fullPath: '/owner/dashboard/$mallId'
      preLoaderRoute: typeof OwnerDashboardMallIdRouteImport
      parentRoute: typeof OwnerRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminManageRoute: typeof AdminManageRoute
  AdminPendingRoute: typeof AdminPendingRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminManageRoute: AdminManageRoute,
  AdminPendingRoute: AdminPendingRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OwnerRouteChildren {
  OwnerGuardsRoute: typeof OwnerGuardsRoute
  OwnerMallsRoute: typeof OwnerMallsRoute
  OwnerRegisterMallRoute: typeof OwnerRegisterMallRoute
  OwnerDashboardMallIdRoute: typeof OwnerDashboardMallIdRoute
  OwnerFloorsMallIdRoute: typeof OwnerFloorsMallIdRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerGuardsRoute: OwnerGuardsRoute,
  OwnerMallsRoute: OwnerMallsRoute,
  OwnerRegisterMallRoute: OwnerRegisterMallRoute,
  OwnerDashboardMallIdRoute: OwnerDashboardMallIdRoute,
  OwnerFloorsMallIdRoute: OwnerFloorsMallIdRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BookingsRoute: BookingsRoute,
  LoginRoute: LoginRoute,
  OwnerRoute: OwnerRouteWithChildren,
  RegisterRoute: RegisterRoute,
  GuardScanRoute: GuardScanRoute,
  MallsMallIdRoute: MallsMallIdRoute,
  MallsIndexRoute: MallsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
