/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MallsIndexRouteImport } from './routes/malls/index'
import { Route as OwnerRegisterMallRouteImport } from './routes/owner/register-mall'
import { Route as OwnerMallsRouteImport } from './routes/owner/malls'
import { Route as MallsMallIdRouteImport } from './routes/malls/$mallId'
import { Route as AdminPendingRouteImport } from './routes/admin/pending'
import { Route as AdminManageRouteImport } from './routes/admin/manage'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as OwnerFloorsMallIdRouteImport } from './routes/owner/floors.$mallId'
import { Route as OwnerDashboardMallIdRouteImport } from './routes/owner/dashboard.$mallId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MallsIndexRoute = MallsIndexRouteImport.update({
  id: '/malls/',
  path: '/malls/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRegisterMallRoute = OwnerRegisterMallRouteImport.update({
  id: '/owner/register-mall',
  path: '/owner/register-mall',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerMallsRoute = OwnerMallsRouteImport.update({
  id: '/owner/malls',
  path: '/owner/malls',
  getParentRoute: () => rootRouteImport,
} as any)
const MallsMallIdRoute = MallsMallIdRouteImport.update({
  id: '/malls/$mallId',
  path: '/malls/$mallId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPendingRoute = AdminPendingRouteImport.update({
  id: '/admin/pending',
  path: '/admin/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminManageRoute = AdminManageRouteImport.update({
  id: '/admin/manage',
  path: '/admin/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerFloorsMallIdRoute = OwnerFloorsMallIdRouteImport.update({
  id: '/owner/floors/$mallId',
  path: '/owner/floors/$mallId',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerDashboardMallIdRoute = OwnerDashboardMallIdRouteImport.update({
  id: '/owner/dashboard/$mallId',
  path: '/owner/dashboard/$mallId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/manage': typeof AdminManageRoute
  '/admin/pending': typeof AdminPendingRoute
  '/malls/$mallId': typeof MallsMallIdRoute
  '/owner/malls': typeof OwnerMallsRoute
  '/owner/register-mall': typeof OwnerRegisterMallRoute
  '/malls/': typeof MallsIndexRoute
  '/owner/dashboard/$mallId': typeof OwnerDashboardMallIdRoute
  '/owner/floors/$mallId': typeof OwnerFloorsMallIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/manage': typeof AdminManageRoute
  '/admin/pending': typeof AdminPendingRoute
  '/malls/$mallId': typeof MallsMallIdRoute
  '/owner/malls': typeof OwnerMallsRoute
  '/owner/register-mall': typeof OwnerRegisterMallRoute
  '/malls': typeof MallsIndexRoute
  '/owner/dashboard/$mallId': typeof OwnerDashboardMallIdRoute
  '/owner/floors/$mallId': typeof OwnerFloorsMallIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/manage': typeof AdminManageRoute
  '/admin/pending': typeof AdminPendingRoute
  '/malls/$mallId': typeof MallsMallIdRoute
  '/owner/malls': typeof OwnerMallsRoute
  '/owner/register-mall': typeof OwnerRegisterMallRoute
  '/malls/': typeof MallsIndexRoute
  '/owner/dashboard/$mallId': typeof OwnerDashboardMallIdRoute
  '/owner/floors/$mallId': typeof OwnerFloorsMallIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/login'
    | '/register'
    | '/admin/dashboard'
    | '/admin/manage'
    | '/admin/pending'
    | '/malls/$mallId'
    | '/owner/malls'
    | '/owner/register-mall'
    | '/malls/'
    | '/owner/dashboard/$mallId'
    | '/owner/floors/$mallId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/login'
    | '/register'
    | '/admin/dashboard'
    | '/admin/manage'
    | '/admin/pending'
    | '/malls/$mallId'
    | '/owner/malls'
    | '/owner/register-mall'
    | '/malls'
    | '/owner/dashboard/$mallId'
    | '/owner/floors/$mallId'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/login'
    | '/register'
    | '/admin/dashboard'
    | '/admin/manage'
    | '/admin/pending'
    | '/malls/$mallId'
    | '/owner/malls'
    | '/owner/register-mall'
    | '/malls/'
    | '/owner/dashboard/$mallId'
    | '/owner/floors/$mallId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminManageRoute: typeof AdminManageRoute
  AdminPendingRoute: typeof AdminPendingRoute
  MallsMallIdRoute: typeof MallsMallIdRoute
  OwnerMallsRoute: typeof OwnerMallsRoute
  OwnerRegisterMallRoute: typeof OwnerRegisterMallRoute
  MallsIndexRoute: typeof MallsIndexRoute
  OwnerDashboardMallIdRoute: typeof OwnerDashboardMallIdRoute
  OwnerFloorsMallIdRoute: typeof OwnerFloorsMallIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/malls/': {
      id: '/malls/'
      path: '/malls'
      fullPath: '/malls/'
      preLoaderRoute: typeof MallsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/register-mall': {
      id: '/owner/register-mall'
      path: '/owner/register-mall'
      fullPath: '/owner/register-mall'
      preLoaderRoute: typeof OwnerRegisterMallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/malls': {
      id: '/owner/malls'
      path: '/owner/malls'
      fullPath: '/owner/malls'
      preLoaderRoute: typeof OwnerMallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/malls/$mallId': {
      id: '/malls/$mallId'
      path: '/malls/$mallId'
      fullPath: '/malls/$mallId'
      preLoaderRoute: typeof MallsMallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pending': {
      id: '/admin/pending'
      path: '/admin/pending'
      fullPath: '/admin/pending'
      preLoaderRoute: typeof AdminPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manage': {
      id: '/admin/manage'
      path: '/admin/manage'
      fullPath: '/admin/manage'
      preLoaderRoute: typeof AdminManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/floors/$mallId': {
      id: '/owner/floors/$mallId'
      path: '/owner/floors/$mallId'
      fullPath: '/owner/floors/$mallId'
      preLoaderRoute: typeof OwnerFloorsMallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/dashboard/$mallId': {
      id: '/owner/dashboard/$mallId'
      path: '/owner/dashboard/$mallId'
      fullPath: '/owner/dashboard/$mallId'
      preLoaderRoute: typeof OwnerDashboardMallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminManageRoute: AdminManageRoute,
  AdminPendingRoute: AdminPendingRoute,
  MallsMallIdRoute: MallsMallIdRoute,
  OwnerMallsRoute: OwnerMallsRoute,
  OwnerRegisterMallRoute: OwnerRegisterMallRoute,
  MallsIndexRoute: MallsIndexRoute,
  OwnerDashboardMallIdRoute: OwnerDashboardMallIdRoute,
  OwnerFloorsMallIdRoute: OwnerFloorsMallIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
